# question_data = [
#     {"question": "A slug's blood is green.", "correct_answer": "True"},
#     {"question": "The loudest animal is the African Elephant.", "correct_answer": "False"},
#     {"question": "Approximately one quarter of human bones are in the feet.", "correct_answer": "True"},
#     {"question": "The total surface area of a human lungs is the size of a football pitch.", "correct_answer": "True"},
#     {"question": "In West Virginia, USA, if you accidentally hit an animal with your car,"
#              " you are free to take it home to eat.", "correct_answer": "True"},
#     {"question": "In London, UK, if you happen to die in the House of Parliament,"
#              " you are entitled to a state funeral.", "correct_answer": "False"},
#     {"question": "It is illegal to pee in the Ocean in Portugal.", "correct_answer": "True"},
#     {"question": "You can lead a cow down stairs but not up stairs.", "correct_answer": "False"},
#     {"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
#     {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "correct_answer": "True"},
#     {"question": "No piece of square dry paper can be folded in half more than 7 times.", "correct_answer": "False"},
#     {"question": "A few ounces of chocolate can to kill a small dog.", "correct_answer": "True"},
# ]

question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Jingle Bells was originally meant for Thanksgiving", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                       "question": "French is an official language in Canada.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                       "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                                       "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "The mitochondria is the powerhouse of the cell.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                       "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                                       "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                       "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "When you cry in space, your tears stick to your face.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Ping-Pong originated in England", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
     "incorrect_answers": ["True"]}]
